/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.99
 * Generated at: 2025-04-21 06:42:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>메시지 갤러리</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Apple SD Gothic Neo', 'Noto Sans KR', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 왼쪽 사이드바 */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 95px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-right: 1px solid #e1e1e1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-logo {\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-menu {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menu-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            color: #888;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menu-item.active {\r\n");
      out.write("            color: #4a8cff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .menu-icon {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메시지 목록 사이드바 */\r\n");
      out.write("        .message-sidebar {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-right: 1px solid #e1e1e1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-header {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-bottom: 1px solid #e1e1e1;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-tabs {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            border-bottom: 1px solid #e1e1e1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tab.active {\r\n");
      out.write("            background-color: #4a8cff;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-list {\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-item {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-bottom: 1px solid #f1f1f1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-item:hover {\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-item.active {\r\n");
      out.write("            background-color: #f0f7ff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-img {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-img img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-info {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-name {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-preview {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            text-overflow: ellipsis;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메인 콘텐츠 영역 */\r\n");
      out.write("        .main-content {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-header {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-bottom: 1px solid #e1e1e1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-profile {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-profile-img {\r\n");
      out.write("            width: 50px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .gallery-profile-img img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 채팅 컨테이너 */\r\n");
      out.write("        .chat-container {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-messages {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-message {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-message.user {\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-bubble {\r\n");
      out.write("            max-width: 70%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border-radius: 18px;\r\n");
      out.write("            word-break: break-word;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-message .chat-bubble {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-bottom-left-radius: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-message.user .chat-bubble {\r\n");
      out.write("            background-color: #4a8cff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-bottom-right-radius: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-bubble.file {\r\n");
      out.write("            background-color: #f0f7ff;\r\n");
      out.write("            border: 1px solid #e1e1e1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-bubble.audio {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메시지 입력 영역 */\r\n");
      out.write("        .chat-input-area {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            border-top: 1px solid #e1e1e1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-input-tools {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tool-button {\r\n");
      out.write("            width: 30px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #888;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-input-field {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            border: 1px solid #e1e1e1;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            resize: none;\r\n");
      out.write("            max-height: 100px;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .chat-send-button {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background-color: #4a8cff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 왼쪽 사이드바 -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-logo\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"#4a8cff\">\r\n");
      out.write("                <path d=\"M12,2C6.486,2,2,6.486,2,12s4.486,10,10,10s10-4.486,10-10S17.514,2,12,2z M12,20c-4.411,0-8-3.589-8-8s3.589-8,8-8 s8,3.589,8,8S16.411,20,12,20z\"/>\r\n");
      out.write("                <path d=\"M13,7h-2v6h2V7z\"/>\r\n");
      out.write("                <path d=\"M12,17L12,17c0.552,0,1-0.448,1-1v0c0-0.552-0.448-1-1-1h0c-0.552,0-1,0.448-1,1v0C11,16.552,11.448,17,12,17z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sidebar-menu\">\r\n");
      out.write("            <a href=\"#\" class=\"menu-item\">\r\n");
      out.write("                <div class=\"menu-icon\">🏠</div>\r\n");
      out.write("                <div>홈</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"menu-item active\">\r\n");
      out.write("                <div class=\"menu-icon\">💬</div>\r\n");
      out.write("                <div>채팅</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"menu-item\">\r\n");
      out.write("                <div class=\"menu-icon\">👥</div>\r\n");
      out.write("                <div>팀</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"menu-item\">\r\n");
      out.write("                <div class=\"menu-icon\">📅</div>\r\n");
      out.write("                <div>캘린더</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"menu-item\">\r\n");
      out.write("                <div class=\"menu-icon\">🔔</div>\r\n");
      out.write("                <div>알림</div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 메시지 목록 사이드바 -->\r\n");
      out.write("    <div class=\"message-sidebar\">\r\n");
      out.write("        <div class=\"message-header\">Messages</div>\r\n");
      out.write("        <div class=\"message-tabs\">\r\n");
      out.write("            <div class=\"tab active\">All</div>\r\n");
      out.write("            <div class=\"tab\">Group</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"message-list\">\r\n");
      out.write("            <div class=\"message-item active\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/4a8cff/ffffff?text=팀\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">집주인 첫째 딸</div>\r\n");
      out.write("                    <div class=\"message-preview\">아 어디야</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"message-item\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/ff4a8c/ffffff?text=여\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">여자친구❤</div>\r\n");
      out.write("                    <div class=\"message-preview\">어디야</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"message-item\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/8cff4a/000000?text=집\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">집주인</div>\r\n");
      out.write("                    <div class=\"message-preview\">일마 오늘 맛있는거 사와</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"message-item\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/ff8c4a/ffffff?text=F\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">fire egg friend</div>\r\n");
      out.write("                    <div class=\"message-preview\">야 근일님 ㄷㄷ ㄹㅇ</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"message-item\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/4aff8c/000000?text=GD\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">고명훈</div>\r\n");
      out.write("                    <div class=\"message-preview\">일마 포샵 GD네 ㅋㅋ</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"message-item\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/8c4aff/ffffff?text=AI\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">스승님</div>\r\n");
      out.write("                    <div class=\"message-preview\">아? 뭐 아? 하면 되는데 그걸 못해?</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"message-item\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/4a8cff/ffffff?text=간\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">간성훈</div>\r\n");
      out.write("                    <div class=\"message-preview\">내 위에 바보</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"message-item\">\r\n");
      out.write("                <div class=\"profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/40/ffd700/000000?text=새\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"message-info\">\r\n");
      out.write("                    <div class=\"message-name\">세미 프로젝트 조</div>\r\n");
      out.write("                    <div class=\"message-preview\">이효석 : 나는 원래 잘생겼...</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 콘텐츠 -->\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"gallery-header\">\r\n");
      out.write("            <div class=\"gallery-profile\">\r\n");
      out.write("                <div class=\"gallery-profile-img\">\r\n");
      out.write("                    <img src=\"https://via.placeholder.com/50/4a8cff/ffffff?text=팀\" alt=\"프로필\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>집주인 첫째 딸</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 채팅 컨테이너 -->\r\n");
      out.write("        <div class=\"chat-container\">\r\n");
      out.write("            <div class=\"chat-messages\" id=\"chatMessages\">\r\n");
      out.write("                <!-- 채팅 메시지들이 여기에 추가됨 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 메시지 입력 영역 -->\r\n");
      out.write("            <div class=\"chat-input-area\">\r\n");
      out.write("                <div class=\"chat-input-tools\">\r\n");
      out.write("                    <button class=\"tool-button\" id=\"fileButton\">\r\n");
      out.write("                        <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                            <path d=\"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4\"/>\r\n");
      out.write("                            <polyline points=\"7 10 12 15 17 10\"/>\r\n");
      out.write("                            <line x1=\"12\" y1=\"15\" x2=\"12\" y2=\"3\"/>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"tool-button\" id=\"imageButton\">\r\n");
      out.write("                        <svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                            <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"/>\r\n");
      out.write("                            <circle cx=\"8.5\" cy=\"8.5\" r=\"1.5\"/>\r\n");
      out.write("                            <polyline points=\"21 15 16 10 5 21\"/>\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"text\" class=\"chat-input-field\" id=\"messageInput\" placeholder=\"메시지를 입력하세요...\">\r\n");
      out.write("                <button class=\"chat-send-button\" id=\"sendButton\">\r\n");
      out.write("                    <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"white\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\r\n");
      out.write("                        <line x1=\"22\" y1=\"2\" x2=\"11\" y2=\"13\"/>\r\n");
      out.write("                        <polygon points=\"22 2 15 22 11 13 2 9 22 2\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // 탭 전환 기능\r\n");
      out.write("            const tabs = document.querySelectorAll('.tab');\r\n");
      out.write("            tabs.forEach(tab => {\r\n");
      out.write("                tab.addEventListener('click', function() {\r\n");
      out.write("                    tabs.forEach(t => t.classList.remove('active'));\r\n");
      out.write("                    this.classList.add('active');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // 메시지 항목 클릭 이벤트\r\n");
      out.write("            const messageItems = document.querySelectorAll('.message-item');\r\n");
      out.write("            messageItems.forEach(item => {\r\n");
      out.write("                item.addEventListener('click', function() {\r\n");
      out.write("                    messageItems.forEach(i => i.classList.remove('active'));\r\n");
      out.write("                    this.classList.add('active');\r\n");
      out.write("                    \r\n");
      out.write("                    // 메시지 선택 시 이름 변경\r\n");
      out.write("                    const name = this.querySelector('.message-name').textContent;\r\n");
      out.write("                    document.querySelector('.gallery-profile h2').textContent = name;\r\n");
      out.write("                    \r\n");
      out.write("                    // 대화 내용 초기화 (새로운 대화상대로 변경)\r\n");
      out.write("                    document.getElementById('chatMessages').innerHTML = '';\r\n");
      out.write("                    \r\n");
      out.write("                    // 초기 메시지 불러오기 - 실제로는 서버에서 가져와야 함\r\n");
      out.write("                    loadInitialMessages(name);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // 초기 메시지 표시\r\n");
      out.write("            loadInitialMessages('집주인 첫째 딸');\r\n");
      out.write("            \r\n");
      out.write("            // 메시지 전송 기능\r\n");
      out.write("            const messageInput = document.getElementById('messageInput');\r\n");
      out.write("            const sendButton = document.getElementById('sendButton');\r\n");
      out.write("            const fileButton = document.getElementById('fileButton');\r\n");
      out.write("            const imageButton = document.getElementById('imageButton');\r\n");
      out.write("            \r\n");
      out.write("            // 메시지 전송 함수\r\n");
      out.write("            function sendMessage() {\r\n");
      out.write("                const messageText = messageInput.value.trim();\r\n");
      out.write("                if (messageText !== '') {\r\n");
      out.write("                    // 사용자 메시지 추가\r\n");
      out.write("                    addMessage('user', 'text', messageText);\r\n");
      out.write("                    \r\n");
      out.write("                    // 입력 필드 초기화\r\n");
      out.write("                    messageInput.value = '';\r\n");
      out.write("                    \r\n");
      out.write("                    // 자동 응답 (실제 서비스에서는 서버로 전송하고 응답을 받아야 함)\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        const responses = [\r\n");
      out.write("                            '알겠어요!',\r\n");
      out.write("                            '네, 확인했습니다.',\r\n");
      out.write("                            '그렇군요. 더 필요한 것이 있으신가요?',\r\n");
      out.write("                            '감사합니다.',\r\n");
      out.write("                            '조금만 기다려주세요.'\r\n");
      out.write("                        ];\r\n");
      out.write("                        const randomResponse = responses[Math.floor(Math.random() * responses.length)];\r\n");
      out.write("                        addMessage('owner', 'text', randomResponse);\r\n");
      out.write("                    }, 1000);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // 전송 버튼 클릭 이벤트\r\n");
      out.write("            sendButton.addEventListener('click', sendMessage);\r\n");
      out.write("            \r\n");
      out.write("            // 엔터 키 입력 이벤트\r\n");
      out.write("            messageInput.addEventListener('keypress', function(e) {\r\n");
      out.write("                if (e.key === 'Enter' && !e.shiftKey) {\r\n");
      out.write("                    e.preventDefault(); // 폼 제출 방지\r\n");
      out.write("                    sendMessage();\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // 파일 첨부 기능\r\n");
      out.write("            fileButton.addEventListener('click', function() {\r\n");
      out.write("                // 실제로는 파일 선택 다이얼로그를 열고 파일을 선택하도록 해야 함\r\n");
      out.write("                // 여기서는 데모를 위해 가상의 파일을 첨부\r\n");
      out.write("                addMessage('user', 'file', { filename: '새문서.pdf', size: '250kB' });\r\n");
      out.write("                \r\n");
      out.write("                // 자동 응답\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    addMessage('owner', 'text', '파일을 받았습니다. 확인해볼게요.');\r\n");
      out.write("                }, 1000);\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // 이미지 첨부 기능\r\n");
      out.write("            imageButton.addEventListener('click', function() {\r\n");
      out.write("                // 실제로는 이미지 선택 다이얼로그를 열고 이미지를 선택하도록 해야 함\r\n");
      out.write("                // 여기서는 데모를 위해 가상의 이미지를 첨부\r\n");
      out.write("                addMessage('user', 'image', 'https://via.placeholder.com/300/cccccc/666666?text=이미지');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // 초기 메시지 불러오기 함수\r\n");
      out.write("        function loadInitialMessages(contactName) {\r\n");
      out.write("            // 실제로는 서버에서 해당 대화상대와의 메시지 기록을 가져와야 함\r\n");
      out.write("            // 여기서는 데모를 위해 고정된 메시지 세트를 사용\r\n");
      out.write("            \r\n");
      out.write("            const messagesByContact = {\r\n");
      out.write("                '집주인 첫째 딸': [\r\n");
      out.write("                    { sender: 'owner', type: 'text', content: '이거 어때? 방에 놔두려고 답장 빨리 해' },\r\n");
      out.write("                    { sender: 'user', type: 'text', content: '그냥 깡패여 나쁘지 않네, 이거나 고쳐줘봐' },\r\n");
      out.write("                    { sender: 'user', type: 'file', filename: '자소서.pdf', size: '120kB' },\r\n");
      out.write("                    { sender: 'owner', type: 'file', filename: '수정본.pdf', size: '150kB' },\r\n");
      out.write("                    { sender: 'owner', type: 'text', content: '너 연습좀 더 해야겠다. 자소서 왜케 못쓰냐?' }\r\n");
      out.write("                ],\r\n");
      out.write("                '여자친구❤': [\r\n");
      out.write("                    { sender: 'owner', type: 'text', content: '어디야' },\r\n");
      out.write("                    { sender: 'user', type: 'text', content: '지금 가는 중' },\r\n");
      out.write("                    { sender: 'owner', type: 'text', content: '언제 오는데' },\r\n");
      out.write("                    { sender: 'user', type: 'text', content: '15분 뒤에' }\r\n");
      out.write("                ],\r\n");
      out.write("                '집주인': [\r\n");
      out.write("                    { sender: 'owner', type: 'text', content: '일마 오늘 맛있는거 사와' },\r\n");
      out.write("                    { sender: 'user', type: 'text', content: '네 무슨 음식 드시고 싶으세요?' },\r\n");
      out.write("                    { sender: 'owner', type: 'text', content: '치킨 사와' }\r\n");
      out.write("                ]\r\n");
      out.write("            };\r\n");
      out.write("            \r\n");
      out.write("            // 해당 대화상대의 메시지가 있으면 표시, 없으면 빈 대화\r\n");
      out.write("            const messages = messagesByContact[contactName] || [];\r\n");
      out.write("            messages.forEach(msg => {\r\n");
      out.write("                if (msg.type === 'text') {\r\n");
      out.write("                    addMessage(msg.sender, 'text', msg.content);\r\n");
      out.write("                } else if (msg.type === 'file') {\r\n");
      out.write("                    addMessage(msg.sender, 'file', { filename: msg.filename, size: msg.size });\r\n");
      out.write("                } else if (msg.type === 'image') {\r\n");
      out.write("                    addMessage(msg.sender, 'image', msg.content);\r\n");
      out.write("                } else if (msg.type === 'audio') {\r\n");
      out.write("                    addMessage(msg.sender, 'audio', msg.duration);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 메시지 추가 함수\r\n");
      out.write("        function addMessage(sender, type, content) {\r\n");
      out.write("            const chatMessages = document.getElementById('chatMessages');\r\n");
      out.write("            const messageDiv = document.createElement('div');\r\n");
      out.write("            messageDiv.classList.add('chat-message');\r\n");
      out.write("            \r\n");
      out.write("            if (sender === 'user') {\r\n");
      out.write("                messageDiv.classList.add('user');\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            const bubble = document.createElement('div');\r\n");
      out.write("            bubble.classList.add('chat-bubble');\r\n");
      out.write("            \r\n");
      out.write("            if (type === 'text') {\r\n");
      out.write("                bubble.textContent = content;\r\n");
      out.write("            } else if (type === 'file') {\r\n");
      out.write("                bubble.classList.add('file');\r\n");
      out.write("                bubble.innerHTML = `\r\n");
      out.write("                    <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${content.filename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong><br>\r\n");
      out.write("                    <small>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${content.size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</small>\r\n");
      out.write("                `;\r\n");
      out.write("            } else if (type === 'image') {\r\n");
      out.write("                bubble.innerHTML = `\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"첨부 이미지\" style=\"max-width: 200px; border-radius: 8px;\">\r\n");
      out.write("                `;\r\n");
      out.write("            } else if (type === 'audio') {\r\n");
      out.write("                bubble.classList.add('audio');\r\n");
      out.write("                bubble.innerHTML = `\r\n");
      out.write("                    <audio controls style=\"width: 100%;\">\r\n");
      out.write("                        <source src=\"#\" type=\"audio/mpeg\">\r\n");
      out.write("                        오디오를 지원하지 않는 브라우저입니다.\r\n");
      out.write("                    </audio>\r\n");
      out.write("                    <small>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</small>\r\n");
      out.write("                `;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            messageDiv.appendChild(bubble);\r\n");
      out.write("            chatMessages.appendChild(messageDiv);\r\n");
      out.write("            \r\n");
      out.write("            // 스크롤을 맨 아래로 이동\r\n");
      out.write("            chatMessages.scrollTop = chatMessages.scrollHeight;\r\n");
      out.write("            \r\n");
      out.write("            // 메시지 미리보기 업데이트 (나중에 선택한 대화상대의 미리보기만 업데이트하도록 수정 필요)\r\n");
      out.write("            if (type === 'text' && sender === 'user') {\r\n");
      out.write("                updateMessagePreview(document.querySelector('.message-item.active'), content);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 메시지 미리보기 업데이트 함수\r\n");
      out.write("        function updateMessagePreview(messageItem, previewText) {\r\n");
      out.write("            if (messageItem) {\r\n");
      out.write("                const previewElement = messageItem.querySelector('.message-preview');\r\n");
      out.write("                if (previewElement) {\r\n");
      out.write("                    previewElement.textContent = previewText;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
